apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-experiment-deployment
  labels:
    schedulingStrategy: meetup
spec:
  replicas: 20
  selector:
    matchLabels:
      app: time-experiment
  template:
    metadata:
      labels:
        app: time-experiment
        schedulingStrategy: meetup
    spec:
      schedulerName: my-custom-scheduler
      containers:
        - name: stress
          image: jfusterm/stress
          command: [ "stress", "--vm", "1", "--vm-bytes", "64m"]
          resources:
            requests:
              memory: "64Mi"
              cpu: "128m"
            limits:
              memory: "128Mi"
              cpu: "256m"
