apiVersion: apps/v1
kind: Deployment
metadata:
  name: eph-deployment
  labels:
    schedulingStrategy: meetup
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eph-deployment
  template:
    metadata:
      labels:
        app: eph-deployment
        schedulingStrategy: meetup
    spec:
      schedulerName: my-custom-scheduler
      containers:
        - name: stress
          image: jfusterm/stress
          command: [ "stress", "--vm", "1", "--vm-bytes", "750m"]
          resources:
            requests:
              memory: "750Mi"
              cpu: "64m"
              ephemeral-storage: "5Mi"
            limits:
              memory: "1024Mi"
              cpu: "128m"
              ephemeral-storage: "10Mi"
          volumeMounts:
            - name: ephermal
              mountPath: /ephermal-volume
      volumes:
        - name: ephermal
          emptyDir: {}


