apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-deployment-replica
  labels:
    schedulingStrategy: meetup
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httperf-replica
  template:
    metadata:
      labels:
        app: httperf-replica
        schedulingStrategy: meetup
    spec:
      serviceAccountName: my-custom-httperf
      schedulerName: my-custom-scheduler
      containers:
      - name: httperf
#        imagePullPolicy: Never
#        image: http-test
        image: us-central1-docker.pkg.dev/involuted-bird-346615/k8s-registry-1/httperf-image
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        resources:
          requests:
            memory: "256Mi"
            cpu: "256m"
          limits:
            memory: "512Mi"
            cpu: "512m"
