apiVersion: apps/v1
kind: Deployment
metadata:
  name: low-stress-deployment-replica
  labels:
    schedulingStrategy: meetup
spec:
  replicas: 3
  selector:
    matchLabels:
      app: low-stress-replica
  template:
    metadata:
      labels:
        app: low-stress-replica
        schedulingStrategy: meetup
    spec:
      schedulerName: my-custom-scheduler
      containers:
        - name: stress
          image: jfusterm/stress
          command: [ "stress", "--cpu", "1", "--vm", "1", "--vm-bytes", "512m"]
          resources:
            requests:
              memory: "512Mi"
              cpu: "128m"
            limits:
              memory: "1024Mi"
              cpu: "256m"
