apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: scheduler
    tier: control-plane
  name: my-custom-scheduler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: scheduler
      tier: control-plane
  replicas: 1
  template:
    metadata:
      labels:
        component: scheduler
        tier: control-plane
        version: second
    spec:
      serviceAccountName: my-custom-scheduler
      containers:
#        - image: scheduler
        - image: us-central1-docker.pkg.dev/involuted-bird-346615/k8s-registry-1/scheduler-image
          name: my-custom-scheduler
#          imagePullPolicy: Never
