apiVersion: v1
kind: Pod
metadata:
  name: huge-pages
  labels:
    schedulingStrategy: meetup
spec:
 schedulerName: my-custom-scheduler
  containers:
  - name: huge-pages
    image: jfusterm/stress
    volumeMounts:
    - mountPath: /hugepages-2Mi
      name: hugepage-2mi
    resources:
      limits:
        hugepages-2Mi: 100Mi
        memory: 100Mi
        cpu: 128m
      requests:
        memory: 100Mi
        cpu: 64m
  volumes:
  - name: hugepage-2mi
    emptyDir:
      medium: HugePages-2Mi
