apiVersion: v1
kind: Pod
metadata:
  name: eph-deployment
  labels:
    schedulingStrategy: meetup
spec:
  schedulerName: my-custom-scheduler
  containers:
    - name: stress
      image: jfusterm/stress
      command: [ "stress", "--cpu", "1"]
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
          ephemeral-storage: "5Mi"
        limits:
          memory: "128Mi"
          cpu: "500m"
          ephemeral-storage: "10Mi"
      volumeMounts:
        - name: ephermal
          mountPath: /ephermal-volume
  volumes:
    - name: ephermal
      emptyDir: {}


