apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-deployment
  labels:
    schedulingStrategy: meetup
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httperf
  template:
    metadata:
      labels:
        app: httperf
        schedulingStrategy: meetup
    spec:
      serviceAccountName: my-custom-httperf
      schedulerName: my-custom-scheduler
      containers:
      - name: httperf
        imagePullPolicy: Never
        image: http-test
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        resources:
          requests:
            memory: "128Mi"
            cpu: "128m"
          limits:
            memory: "256Mi"
            cpu: "512m"
