apiVersion: apps/v1
kind: Deployment
metadata:
  name: low-stress-deployment
  labels:
    schedulingStrategy: meetup
spec:
  replicas: 2
  selector:
    matchLabels:
      app: low-stress
  template:
    metadata:
      labels:
        app: low-stress
        schedulingStrategy: meetup
    spec:
      schedulerName: my-custom-scheduler
      containers:
        - name: stress
          image: jfusterm/stress
          command: [ "stress", "--cpu", "1"]
          resources:
            requests:
              memory: "128Mi"
              cpu: "128m"
            limits:
              memory: "256Mi"
              cpu: "256m"
