apiVersion: apps/v1
kind: Deployment
metadata:
  name: low-stress-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      schedulerName: my-custom-scheduler
      containers:
        - name: stress
          image: jfusterm/stress
          command: [ "stress", "--cpu", "1", "-m", "1", "--vm-bytes", "128M", "--io", "1", "--hdd", "2"]
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
