apiVersion: apps/v1
kind: Deployment
metadata:
  name: low-stress-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
      - name: stress
        image: jfusterm/stress
        command: ["stress", "--cpu", "10"]
