apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: scheduler
    tier: control-plane
  name: my-custom-scheduler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: scheduler
      tier: control-plane
  replicas: 1
  template:
    metadata:
      labels:
        component: scheduler
        tier: control-plane
        version: second
    spec:
      serviceAccountName: my-custom-scheduler
      containers:
        - image: scheduler
          name: my-custom-scheduler
          imagePullPolicy: Never
          resources:
            requests:
              memory: "100Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"